/**
 * dashboard面板获取最上面的四个统计信息
 */
export const DASHBOARD_GET_STATISTICS = 'DASHBOARD_GET_STATISTICS'
export const DASHBOARD_GET_STATISTICS_SUCCESS = 'DASHBOARD_GET_STATISTICS_SUCCESS'
export const DASHBOARD_GET_STATISTICS_FAILURE = 'DASHBOARD_GET_STATISTICS_FAILURE'