/**
 * 日志分析页面获取最上面的四个统计信息
 */
export const ERRORLOG_GET_STATISTICS = 'ERRORLOG_GET_STATISTICS'
export const ERRORLOG_GET_STATISTICS_SUCCESS = 'ERRORLOG_GET_STATISTICS_SUCCESS'
export const ERRORLOG_GET_STATISTICS_FAILURE = 'ERRORLOG_GET_STATISTICS_FAILURE'